version: 2.1

defaults: &defaults
  working_directory: ~/feathery-react
  docker:
    - image: cimg/node:14.17

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - package-dependencies-{{ checksum "package-lock.json" }}
          - package-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: package-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/feathery-react
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn test:lint
      - run: yarn test

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build

  persist:
    <<: *defaults
    steps:
      - store_artifacts:
          path: .

  publish:
    <<: *defaults
    steps:
      - run: echo 'Publishing...'

workflows:
  version: 2.1
  pipeline:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
      - persist:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
      - approve:
          type: approval
          requires:
            - persist
      - publish:
          requires:
            - approve
